[package]
name = "structured-commenting-parser"
version = "0.1.0"
authors = ["Logan King <seanloganking@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ptree = "0.3.2"
